### ISSUE TITLE
usage multiple schema test case / code example

### ISSUE THREAD

**Issue by eflauzo** [stealthly/go-avro#1]
Project is looking very interesting, but it misses example how to load multiple avro schemas and then use them. 

I can not see in test cases example where one would load few avro schemas where one is depended on another, and then serialize/deserialize message.

**Comment by serejja** [comment]
Hey @eflauzo, thank you and Michael for providing me with some of your work. I managed to integrate some of your code into go-avro now, maybe will add some more stuff a bit later. For now (regarding this issue) I've added some code examples showing how to use schema loading.

Thanks!
