### ISSUE TITLE
Generic reader example for complex of complex types please

### ISSUE THREAD

**Issue by pm-kartik-sura** [stealthly/go-avro#20]
It would help a lot if there is an example to encode and decode a complex of complex type using generic datum.
I am having a hard time figuring it out.

**Comment by serejja** [comment]
Hey @pm-kartik-sura, I updated [this](https://github.com/stealthly/go-avro/blob/master/examples/generic_datum/generic_datum.go) example with complex types. You may pass parent schema to all child GenericRecords for now, but this will probably be changed when API is stabilized.

**Comment by pm-kartik-sura** [comment]
Thanks a lot. I was trying to figure it out since a long time :)
