### ISSUE TITLE
GenericDatum: handle enums represented as strings

### ISSUE THREAD

**Issue by arunmk** [stealthly/go-avro#35]
It would be very useful to allow one to do something like:
genericrecord.Set("enumname", "string")

This is currently not possible in the GenericDatum type.

**Comment by arunmk** [comment]
This is fixed by:
Pull: https://github.com/stealthly/go-avro/pull/37
Commit: https://github.com/arunmk/go-avro/commit/1cae0646d2c616d120badd4fc25c32fc6f796abf

The commit has tests updated.

**Comment by serejja** [comment]
Merged to master. Thanks
