### ISSUE TITLE
GenericDatum: Process default values correctly

### ISSUE THREAD

**Issue by arunmk** [stealthly/go-avro#36]
Currently:
1. Default values are not processed well in GenericDatum. They are not set at all.
2. If a number literal is used as a default value, it is converted internally to `float64` due to GoLang JSON unmarshalling.

The above need to be fixed.

**Comment by arunmk** [comment]
This is fixed by:
Pull: https://github.com/stealthly/go-avro/pull/37
Commit: https://github.com/arunmk/go-avro/commit/7eb45b451f12afb7602dbe40e462faf0d6ed52dc

The commit has tests updated.

**Comment by serejja** [comment]
Merged to master. Thanks
