### ISSUE TITLE
Basic Documentation / Readme

### ISSUE THREAD

**Issue by tristanz** [stealthly/go-avro#7]
It would be great to have a basic README.md to explain the status of this project.  A simple usage example plus a note about what is and is not supported would go a long way.  Alternatively, if this library is just for internal use, even a note saying that would be useful.

**Comment by joestein** [comment]
@tristanz we recently got back to working on this. I think at this point it should support everything but recursive types (as far as the Serialization/Deserialization goes). 

We started integrating it into our go kafka client https://github.com/stealthly/go_kafka_client to use the confluent schema registry http://confluent.io/docs/current/schema-registry/docs/index.html and get things working as typical kafka implementation with avro exist on the JVM (but now with Go of course). 

I asked @serejja to writeup the README here when he gets a sec. 

Once go-avro is integrated into go_kafka_client we hope to get more use and schemas going through to help round out any issues there might be. Appreciate any feedback you have, thanks!

**Comment by joestein** [comment]
@tristanz README has been updated with some examples. We also integrated the library with our Kafka library if you are interested in an implementation example https://github.com/stealthly/go-kafka/blob/master/scala_go_kafka.go with schema registry.
